# Creates a gitopscluster resource
#
# Requires:
#  Openshift-GitOps operator be installed in the project "openshift-gitops"
#  Placement resource "global-gitops" exists
#  A clusterSet is bound to the openshift-gitops namespace 
---
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: rhacm-gitopscluster
  namespace: openshift-gitops
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1alpha1
    name: global-gitops
    namespace: openshift-gitops