# Creates a ManagedClusterSetBinding to the openshift-gitops project
---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: ManagedClusterSetBinding
metadata:
  name: global-gitops-binding
  namespace: openshift-gitops
spec:
  clusterSet: global